/** @type {import('tailwindcss').Config} */
module.exports = {
  /* Comma-separated IDs break utilities (e.g. .hidden → display:none on each id). Use :is(). */
  important:
    ':is(#tfilot_single_page, #friday_single_page, #friday_single_page_plag)',
  content: [
    './html/tfilot_single_page.html',
    './html/friday_single_page.html',
    './html/friday_single_page_plag.html',
    './html/prayer_times_grouped_single_page.html',
    './html/prayer_times_friday_single_page.html',
    './html/day_times_inner_single_page.html',
    './scripts/present-next-page.js',
    './styles/src/**/*.css',
  ],
  theme: {
    extend: {
      colors: {
        'on-background': '#1b1c1a',
        primary: '#6a5d41',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e3e2df',
        'secondary-container': '#d7e2ff',
        'tertiary-fixed': '#e1e0f8',
        'on-tertiary-fixed': '#191a2b',
        'on-tertiary-fixed-variant': '#444558',
        'inverse-on-surface': '#f2f1ed',
        'inverse-primary': '#d6c5a2',
        'surface-container-low': '#f4f4f0',
        'primary-fixed-dim': '#d6c5a2',
        'on-tertiary-container': '#47495c',
        'inverse-surface': '#2f312e',
        'surface-dim': '#dbdad6',
        'primary-container': '#c9b896',
        'tertiary-container': '#b8b8cf',
        'surface-bright': '#faf9f5',
        'on-secondary-fixed-variant': '#3c475d',
        error: '#ba1a1a',
        surface: '#faf9f5',
        'on-primary': '#ffffff',
        'surface-variant': '#e3e2df',
        tertiary: '#5c5d71',
        'outline-variant': '#cec5b9',
        'secondary-fixed-dim': '#bbc6e2',
        secondary: '#545e76',
        'on-surface': '#1b1c1a',
        'on-secondary': '#ffffff',
        'surface-tint': '#6a5d41',
        'surface-container': '#efeeea',
        'primary-fixed': '#f3e1bc',
        'secondary-fixed': '#d7e2ff',
        'surface-container-high': '#e9e8e4',
        background: '#faf9f5',
        'on-secondary-fixed': '#101b30',
        outline: '#7d766b',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#5a647c',
        'on-surface-variant': '#4b463c',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#c5c4dc',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#231a05',
        'on-primary-fixed-variant': '#51452b',
        'on-primary-container': '#54492e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '32px',
        'item-gap': '16px',
        unit: '8px',
        gutter: '40px',
        'section-margin': '80px',
      },
      fontFamily: {
        'display-time': ['Work Sans', 'system-ui', 'sans-serif'],
        'label-caps': ['Work Sans', 'system-ui', 'sans-serif'],
        'body-md': ['Work Sans', 'system-ui', 'sans-serif'],
        'headline-md': ['Work Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Work Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Work Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-time': [
          '120px',
          { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-caps': [
          '18px',
          { lineHeight: '100%', letterSpacing: '0.1em', fontWeight: '700' },
        ],
        'body-md': ['22px', { lineHeight: '150%', fontWeight: '400' }],
        'headline-md': ['40px', { lineHeight: '130%', fontWeight: '600' }],
        'body-lg': ['28px', { lineHeight: '150%', fontWeight: '500' }],
        'headline-lg': ['56px', { lineHeight: '120%', fontWeight: '700' }],
      },
      boxShadow: {
        glass: '0 8px 32px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  plugins: [],
};
